name: btc_address_analyzer
version: 2.0.0
description: Bitcoin Base58 address decoder and analyzer with checksum validation and payload parsing.
author: BitMorphX
license: Apache-2.0
language: Python
python_version: ">=3.8"
entry_point: btc_address_analyzer.py
repository: https://github.com/BitMorphX/btc_address_analyzer
tags:
  - bitcoin
  - base58
  - checksum
  - cli
  - python
  - crypto
  - address-validation
  - hash160
  - analyzer
  - learning
dependencies:
  - base58
  - termcolor
dev_dependencies:
  - black
  - pylint
  - pytest
